export const TARGET_FIELDS = [
    { key: "opty_no", label: "Opty No (cari Opportunity yang cocok)", required: true },
    { key: "project_details", label: "Project Details" },
    { key: "sales_type_code", label: "Sales Type" },
    { key: "pq_price", label: "PQ Price" },
    { key: "pq_total", label: "PQ Total" },
    { key: "pks_no", label: "No PKS" },
    { key: "pks_url", label: "Link PKS" },
    { key: "pks_status_code", label: "Status PKS" },
    { key: "po_start_date", label: "Start Date PO" },
    { key: "po_end_date", label: "End Date PO" },
    { key: "po_no", label: "No PO" },
    { key: "po_url", label: "Link PO" },
    { key: "po_status_code", label: "Status PO" },
    { key: "cr_no", label: "No CR" },
    { key: "cr_url", label: "Link CR" },
    { key: "cr_status_code", label: "Status CR" },
    { key: "other_doc_no", label: "No Dokumen Lain" },
    { key: "other_doc_url", label: "Link Dokumen Lain" },
    { key: "other_doc_status_code", label: "Status Dokumen Lain" },
  ];