export const TARGET_FIELDS = [
    { key: "opty_no", label: "Opty No" },
    { key: "sales_qualified", label: "Sales Qualified" },
    { key: "client_name", label: "Client Name", required: true },
    { key: "service_type_code", label: "Service Type" },
    { key: "requirement_summary", label: "Requirement Summary" },
    { key: "opty_status_code", label: "Opty Status" },
    { key: "progress_notes", label: "Progress Notes" },
    { key: "estimated_deal_amount", label: "Estimated Deal" },
    { key: "detail_requirement", label: "Detail Requirement" },
    { key: "client_type_code", label: "Client Type" },
    { key: "sales_pic_name", label: "Sales PIC", required: true },
    { key: "last_communication_date", label: "Last Communication" },
    { key: "bante_score", label: "BANTE Score" },
    { key: "dropped_reason", label: "Dropped Reason" },
    { key: "position_name", label: "Positions" },
    { key: "level_code", label: "Level" },
    { key: "headcount_target", label: "Headcount" },
    { key: "price_amount", label: "Price" },
  ];