export const TARGET_FIELDS = [
    { key: "employee_no", label: "Employee No (cari Employee yang cocok)", required: true },
    { key: "client_name", label: "Client Name (cari Requisition yang cocok)" },
    { key: "start_date", label: "Start Date" },
    { key: "end_date", label: "End Date" },
    { key: "status_code", label: "Status" },
    { key: "talent_track_code", label: "Talent Track" },
    { key: "current_grading", label: "Current Grading" },
    { key: "current_salary_grade_code", label: "Current Salary Grade" },
    { key: "price_amount", label: "Price" },
    { key: "current_skill", label: "Current Skill" },
    { key: "current_certification", label: "Current Certification" },
    { key: "performance_appraisal_result", label: "Performance Appraisal Result" },
    { key: "performance_review_result", label: "Performance Review Result" },
    { key: "basic_salary_amount", label: "Basic Salary" },
    { key: "functional_allowance_amount", label: "Functional Allowance" },
    { key: "transport_allowance_amount", label: "Transport Allowance" },
    { key: "project_allowance_amount", label: "Project Allowance" },
    { key: "accommodation_allowance_amount", label: "Accommodation Allowance" },
    { key: "field_allowance_amount", label: "Uang Lapangan" },
    { key: "overtime_allowance_amount", label: "Overtime" },
    { key: "notes", label: "Notes" },
  ];